version: '3.7'
services:
  hero-dashboard:
    image: hero-dashboard:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        env: ${BUILD_ENV:-prod}
    ports:
      - 8080:80